# a copy from https://github.com/nonebot/nonebot2
template: $CHANGES
category-template: "### $TITLE"
name-template: "Release v$RESOLVED_VERSION ðŸŒˆ"
tag-template: "v$RESOLVED_VERSION"
change-template: "- $TITLE [@$AUTHOR](https://github.com/$AUTHOR) ([#$NUMBER]($URL))"
change-title-escapes: '\<&'
categories:
  - title: "ðŸ’¥ ç ´åæ€§å˜æ›´"
    labels:
      - "ç ´åæ€§"
      - "Breaking"
  - title: "ðŸ¦„ æ–°åŠŸèƒ½å®žçŽ°"
    labels:
      - "åŠŸèƒ½"
      - "å®žçŽ°"
      - "feature"
  - title: "ðŸ¦„ æ–°åŠŸèƒ½å®žçŽ°"
    labels:
      - "å¢žå¼º"
      - "ä¼˜åŒ–"
      - "æ”¹è¿›"
      - "optimize"
      - "improve"
      - "enhancement"
  - title: "ðŸ› Bug ä¿®å¤"
    labels:
      - "ä¿®å¤"
      - "è§£å†³"
      - "fix"
      - "bugfix"
      - "bug"
  - title: "ðŸ“ æ–‡æ¡£"
    labels:
      - "README.md"
      - "æ–‡æ¡£"
      - "documentation"
  - title: "ðŸ”€ ä¾èµ–æ”¹åŠ¨"
    labels:
      - "ä¾èµ–"
  - title: "ðŸ’« æ‚é¡¹"
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch