from wanmeibbskit.utils import URL

PWCGAPI = URL('https://pwgcapi.wanmei.com/')
USERAPI = URL('https://user.laohu.com/')
TOKEN_TO_COOKIE = URL('http://i.laohu.com/tokenToCookie?')

PROD_ZXSJ = URL('zxsj.wanmei.com')
PROD_ZXSJ_INAPP = URL('zx2-inapp.games.wanmei.com')
PROD_DOULIU = URL('douliu.wanmei.com')
PARENTS_CENTER = URL('http://www.wanmei.com/jiazhang')

SNAP_UP = URL('https://douliu.wanmei.com/pwgcnew/app/html/snapup.html')
PRODUCT_DETAIL = URL('https://douliu.wanmei.com/pwgcnew/app/html/product-detail.html?productId=')
PACKAGE = URL('https://douliu.wanmei.com/pwgcnew/app/html/package.html?oneAppId=')
GAME_DETAIL = URL('https://douliu.wanmei.com/pwgcnew/#/game-detail?gameId=')
RECORDS_TAG = URL('https://douliu.wanmei.com/pwgcnew/app/html/records.html?pageTag=1')
GROWTH_SCORE_EXPLAIN = URL('https://douliu.wanmei.com/pwgcnew/app/html/growth-score-explain.html#growth')
WRITE_CENTER = URL('https://douliu.wanmei.com/pwgcnew/app/html/write-center.html')
WRITER_DATA = URL('https://douliu.wanmei.com/pwgcnew/app/html/writer-data.html')
CIRCLE = URL('https://douliu.wanmei.com/m/circle.html?circleId=')
CHANNEL_SHARE = URL('https://douliu.wanmei.com/pwgcnew/app/html/channel-share.html')
WORLD_SHARE = URL('https://douliu.wanmei.com/pwgcnew/app/html/world-share.html')
WALLET_HOME = URL('https://douliu.wanmei.com/pwgcnew/app/html/wallet-home.html')
DETAIL2 = URL('https://pwgcapi.wanmei.com/source/plugin/wanmei_api/public/html/detail2.html?tid=')
DOULIU_PRIVACY = URL('https://safe.games.laohu.com/www/douliu/privacy.html')
RAW_CONTRACT = URL('https://safe.games.laohu.com/www/douliu/contract.html')
CONTRACT = URL('https://safestatic.games.laohu.com/www/contract.html')
GAME_PRIVACY = URL('https://safestatic.games.laohu.com/www/privacy.html')
AFFECT_GAME_LIST = URL('https://douliu.wanmei.com/safestatic/affectGamelist.html')
INDEX = URL('https://safestatic.games.laohu.com/main_station/appgame/cancellation/index.html')
FORUM = URL('https://douliu.wanmei.com/pwgcnew/app/html/forum.html?articleId=')
ARTICLE_DETAIL_MOBILE = URL('https://douliu.wanmei.com/m/article-detail.html?aid=')
ARTICLE_DETAIL = URL('https://douliu.wanmei.com/publish/article-detail.html?')
BIND_NEW = URL('https://douliu.wanmei.com/pwgcnew/app/html/bindnew.html?type=kf')
RECORDS_TAG2 = URL('https://douliu.wanmei.com/pwgcnew/app/html/records.html?pageTag=2')
CIRCLE_SIGN_RULE = URL('https://douliu.wanmei.com/pwgcnew/app/html/circle-sign-rule.html')
YICARTOON = URL('https://douliu.wanmei.com/pwgcnew/app/html/yicartoon.html?gameId=32')
RECORDS = URL('https://app.games.wanmei.com/pwgc/html/records.html?pageTag=1')
TASK_LIST = URL('https://douliu.wanmei.com/pwgcnew/app/html/task-list.html')
OPINION = URL('https://douliu.wanmei.com/pwgcnew/app/html/opinion.html')
TOPIC = URL('https://douliu.wanmei.com/m/topic.html?topicId=')
VIP = URL('https://douliu.wanmei.com/pwgcnew/app/html/vip.html')
